# provider: "openai"
# model: "gpt-3.5-turbo"
# api_key: "sk-xxxxxx"  # 또는 환경변수 사용 권장

# provider: "azure"
# model: "gpt-35-turbo"
# azure_endpoint: "https://<your-resource>.openai.azure.com/"
# azure_deployment: "your-deployment-name"
# azure_api_key: "your-azure-api-key"
# azure_api_version: "2023-05-15"

provider: "openai"  # LM Studio는 OpenAI API 호환
model: "gpt-4-turbo"
api_key: "lm-studio"  # LM Studio는 API Key 없이 사용 가능
base_url: "http://192.168.0.23:2345/v1"
